# Конфигурационный файл для IRC-клиента

[ircServer]	# Параметры IRC сервера
ircServerHost = "irc.efnet.org"  # Адрес сервера IRC
ircServerPort = 6667             # Порт сервера IRC
ircServerPass = ""               # Пароль сервера (в основном для ZNC)

[ircClient]
ircBotUser = "bot"		# Никнейм бота
ircBotNick = "ashen"		# Юзернейм бота
ircBotNalt = "InfoIP, ipBot"    # Альтернативные ники
ircBotRnam = "Ashen Bot"	# Реал нейм бота
ircBotNspw = ""			# Пароль NickServ (в EFNet не нужен)
ircBotChan = "#bots"   # Каналы, к которым присоединяется бот
ircBotAdmi = "const, boost"   # Ники администраторов бота
ircBotAcon = true
ircBotCsym = "."
ircBotRcon = ""
ircBotDccv = "IPinfo IRC Bot (Linux)"

[botComset] # Параметры дополнительных функций бота
ipInfoToken = "a21daf8ef45e36" # Токен сервиса ipinfo.io
logFileName = "efnet.irc.log"  # Имя лог-файла бота
hidePingPong = true            # Скрывать PING? PONG! сервера
outputConsole = true          # Вывод на консоль
outputRawData = true          # Log RAW IRC data from server
outputDebug = false            # Флаг отладочного режима
botConfigured = true           # Флаг, что дефолтная конфигурация отредактирована
