# Конфигурационный файл для IRC-клиента

[ircServer]	# Параметры IRC сервера
ircServerHost = "localhost"    # Адрес сервера IRC
ircServerPort = 6667           # Порт сервера IRC
ircServerPass = ""             # Пароль IRC сервера (ZNC)

[ircClient] # Параметры IRC клиента
ircBotUser = "bot"
ircBotNick = "aspen"
ircBotNalt = "cxBot, ipBot"  # Альтернативные ники
ircBotRnam = "InfoBot"
ircBotNspw = ""
ircBotChan = "#rand, #ircx"   # Каналы, к которым присоединяется бот
ircBotAdmi = "const, boost"    # Ники администраторов бота
ircBotAcon = true
ircBotCsym = "."
ircBotRcon = ""
ircBotDccv = "IPinfoIRC Bot (Linux)"

[botComset] # Параметры дополнительных функций бота
ipInfoToken = "a21daf8ef45e36" # Токен сервиса ipinfo.io
logFileName = "mircd.loc.log"  # Имя лог-файла бота
hidePingPong = true            # Скрывать PING? PONG! сервера
outputConsole = true           # Вывод на консоль
outputRawData = true           # Log RAW IRC data from server
outputDebug = true             # Флаг отладочного режима
botConfigured = true           # Флаг, что дефолтная конфигурация отредактирована
