# Конфигурационный файл для IRC-клиента

[ircServer]	# Параметры IRC сервера
ircServerHost = "irc.rizon.net"   # Адрес сервера IRC
ircServerPort = 7000              # Порт сервера IRC
ircServerPass = ""                # Пароль сервера (в основном для ZNC)

[ircClient]
ircBotUser = "bot"
ircBotNick = "ashen"
ircBotNalt = "InfoIP, ipBot" # Альтернативные ники
ircBotRnam = "IPinfo Bot: .ip <host>"
ircBotNspw = "lamodrom"
ircBotChan = "#rand, #ircx"   # Каналы, к которым присоединяется бот
ircBotAdmi = "const, boost"   # Ники администраторов бота
ircBotAcon = true
ircBotCsym = "."
ircBotRcon = ""
ircBotDccv = "IPinfo IRC Bot (Linux)"

[botComset] # Параметры дополнительных функций бота
ipInfoToken = "a21daf8ef45e36" # Токен сервиса ipinfo.io
logFileName = "rizon.irc.log"  # Имя лог-файла бота
hidePingPong = true            # Скрывать PING? PONG! сервера
outputConsole = false           # Вывод на консоль
outputRawData = false          # Log RAW IRC data from server
outputDebug = false            # Флаг отладочного режима
botConfigured = true          # Флаг, что дефолтная конфигурация отредактирована
