# Конфигурационный файл для IRC-клиента

[ircServer]	# Параметры IRC сервера
ircServerHost = "irc.rizon.net"   # Адрес сервера IRC
ircServerPort = 7000              # Порт сервера IRC
ircServerPass = ""                # Пароль сервера (ZNC и сервера с паролем)

[ircClient] # Параметры IRC клиента
ircBotUser = "cbot"               # Имя пользователя бота
ircBotNick = "CxxBot"             # Основной ник бота
ircBotNalt = "CxxBot_, CBot1"     # Альтернативные ники
ircBotRnam = "IP info Bot"        # Реальное имя (RealName)
ircBotNspw = ""                   # Пароль NickServ (двойные кавычки обязательны)
ircBotChan = "#test, #ircx"       # Каналы, к которым присоединяется бот
ircBotAdmi = "const, aesh"        # Ники администраторов бота
ircBotAcon = false                # Флаг автозапуска (true/false)
ircBotCsym = "."                  # Символ команды бота
ircBotRcon = ""                   # Сообщения серверу при соединении
ircBotDccv = "C++ IRC bot"        # CTCP DCC VERSION

[botComset] # Параметры дополнительных функций бота
ipInfToken = "xxxxxxxxxxxxxx"	  # Токен сервиса ipinfo.io
debugMode = false                 # Флаг отладочного режима
logFileName = "ircbot.log"        # Имя лог-файла бота в директории ./log
